package com.example.hotwheelscollectors.data.local.entities

import androidx.room.Embedded
import androidx.room.Relation

/**
 * Data class representing a car entity with its associated search keywords.
 * This is used for Room database queries that need to fetch cars along with their keywords.
 */
data class CarWithSearchKeywords(
    @Embedded val car: CarEntity,

    @Relation(
        parentColumn = "id",
        entityColumn = "carId"
    )
    val searchKeywords: List<SearchKeywordEntity>
) {
    /**
     * Get the search keywords as a simple list of strings
     */
    fun getKeywordsAsStrings(): List<String> {
        return searchKeywords.map { it.keyword }
    }

    /**
     * Check if the car has any search keywords
     */
    fun hasKeywords(): Boolean {
        return searchKeywords.isNotEmpty()
    }

    /**
     * Get the number of search keywords for this car
     */
    fun getKeywordCount(): Int {
        return searchKeywords.size
    }

    /**
     * Check if the car has a specific keyword
     */
    fun hasKeyword(keyword: String): Boolean {
        return searchKeywords.any { it.keyword.equals(keyword, ignoreCase = true) }
    }

    /**
     * Get keywords that match a specific query
     */
    fun getMatchingKeywords(query: String): List<String> {
        return searchKeywords
            .map { it.keyword }
            .filter { it.contains(query, ignoreCase = true) }
    }

    /**
     * Get keywords sorted by priority
     */
    fun getKeywordsByPriority(): List<SearchKeywordEntity> {
        return searchKeywords.sortedByDescending { it.priority }
    }

    /**
     * Get auto-generated keywords
     */
    fun getAutoGeneratedKeywords(): List<SearchKeywordEntity> {
        return searchKeywords.filter { it.isAutoGenerated }
    }

    /**
     * Get manually added keywords
     */
    fun getManualKeywords(): List<SearchKeywordEntity> {
        return searchKeywords.filter { !it.isAutoGenerated }
    }

    /**
     * Check if car has any premium keywords (high priority)
     */
    fun hasPremiumKeywords(): Boolean {
        return searchKeywords.any { it.priority > 5 }
    }

    /**
     * Get keywords for a specific category
     */
    fun getKeywordsByCategory(category: String): List<SearchKeywordEntity> {
        return searchKeywords.filter { it.keyword.contains(category, ignoreCase = true) }
    }
}