package com.example.hotwheelscollectors.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Entity representing search keywords associated with cars.
 * This allows for efficient searching and filtering of cars based on keywords.
 */
@Entity(
    tableName = "search_keywords",
    foreignKeys = [
        ForeignKey(
            entity = CarEntity::class,
            parentColumns = ["id"],
            childColumns = ["carId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["carId"]),
        Index(value = ["keyword"]),
        Index(value = ["carId", "keyword"], unique = true)
    ]
)
data class SearchKeywordEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * The ID of the car this keyword is associated with
     */
    val carId: String,

    /**
     * The search keyword text
     */
    val keyword: String,

    /**
     * Timestamp when this keyword was added
     */
    val timestamp: Long = System.currentTimeMillis(),

    /**
     * Priority/weight of this keyword (higher values = more important)
     */
    val priority: Int = 1,

    /**
     * Whether this keyword was automatically generated or manually added
     */
    val isAutoGenerated: Boolean = false,

    /**
     * Category of the keyword (e.g., "brand", "series", "color")
     */
    val category: String = "",

    /**
     * Additional metadata for the keyword
     */
    val metadata: String = ""
) {
    /**
     * Check if this keyword is valid
     */
    fun isValid(): Boolean {
        return keyword.isNotBlank() && carId.isNotBlank()
    }

    /**
     * Get a normalized version of the keyword for consistent searching
     */
    fun getNormalizedKeyword(): String {
        return keyword.trim().lowercase()
    }

    /**
     * Check if this keyword matches a search query
     */
    fun matchesQuery(query: String): Boolean {
        return getNormalizedKeyword().contains(query.lowercase())
    }

    /**
     * Check if this is a high priority keyword
     */
    fun isHighPriority(): Boolean {
        return priority > 5
    }

    /**
     * Check if this keyword belongs to a specific category
     */
    fun belongsToCategory(categoryName: String): Boolean {
        return category.equals(categoryName, ignoreCase = true)
    }
}